name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [29]
        target: [default]

    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.9.1
      with:
        access_token: ${{ github.token }}
    
    - name: checkout 
      uses: actions/checkout@v3
    
    - name: set up JDK 11
      uses: actions/setup-java@v3.4.0
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      
    - name: Pring gradle version
      run: gradle --version

    # - name: Grant execute permission for gradlew
    #  run: chmod +x gradlew

    # - name: Grant execute permission for gradle
    #  run: chmod +x gradle
      
    # - name: AVD cache
    #   uses: actions/cache@v3
    #   id: avd-cache
    #   with:
    #     path: |
    #       ~/.android/avd/*
    #       ~/.android/adb*
    #     key: avd-${{ matrix.api-level }}
        
    - name: create AVD and generate snapshot for caching
      if: steps.avd-cache.outputs.cache-hit != 'true'
      uses: reactivecircus/android-emulator-runner@v2.24.0
      with:
        api-level: ${{ matrix.api-level }}
        force-avd-creation: false
        emulator-options: -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
        disable-animations: false
        script: echo "Generated AVD snapshot for caching."
    
    - name: Build with Gradle
      run: gradle build
      
    - name: Printing directory structure
      run: pwd && ls
    
    - name: Run tests
      uses: reactivecircus/android-emulator-runner@v2.24.0
      with:
        api-level: ${{ matrix.api-level }}
        force-avd-creation: false
        emulator-options: -no-snapshot-save -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
        disable-animations: true
        target: ${{ matrix.target }}
        arch: x86_64
        profile: Nexus 5
        script: gradle connectedAndroidTest
        
    - name: Zip build reports
      id: zipBuildReports
      if: always()
      run: zip -r build-reports.zip app/build/reports
    
    - name: Upload build reports
      if: always() && steps.zipBuildReports.outcome == 'success'
      uses: actions/upload-artifact@v2
      with:
        name: build-reports
        path: build-reports.zip
        retention-days: 3
